apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloprod
  namespace: lasampleprod
  labels:
    app: helloprod
spec:
  selector:
    matchLabels:
      app: helloprod
  template:
    metadata:
      labels:
        app: helloprod
    spec:
      containers:
      - name: helloprod
        image: linuxacademycontent/gitops:hellov1.2
